export default {
  en: {
    common: {
      width: "Width",
      height: "Height",
      pageWidth: "Page Width",
      pageHeight: "Page Height",
      cellWidth: "Label Width",
      cellHeight: "Label Height",
      count: "Label count",
      cellPadding: "Label Padding",
      cellPaddingLeft: "Label Padding Left",
      cellPaddingTop: "Label Padding Top",
      pageMargin: "Page Margin",
      pageMarginLeft: "Page Margin Left",
      pageMarginTop: "Page Margin Top",
      new:'New Template',
      applyLayout:'Apply Layout',
    },
    header: {
      menu: {
        dashboard:'Home',
        home:'Home',
        designer: 'Editor',
        editor:'Editor',
        data: 'Data',
        integrations:'Integrations',
        templates: 'Templates Hub',
        layouts: 'Layouts',
        apps:'Apps',
        new:'New Template',
        maker:'Maker',
        save: "Save",
        print: "Print",
        banners:'Banners',
        popups:'Popups',
        apps:'Apps',
        labels:'Labels',
        email:'Email',
        thumbnails:'Thumbnails',
        products:'Products',
        more:'More',
        studio:'Studio',
        settings:'Settings',
        generators:'Generators',
      }
    },
    editor: {
      settings: {
        btnDelete: 'Delete selected',
        btnDuplicate: 'Duplicate',
        btnGroup:'Group',
        btnZoomIn: 'Zoom In',
        btnZoomOut: 'Zoom Out',
        fitInViewport:'Fit In Viewport',
        fillInViewport:'Fill In Viewport',
        btnMoveUp: 'Move Up',
        btnMoveDown: 'Move Down',
        btnClearAll: 'Clear all'
      }
    },
    context:{
      delete:'Delete',
      duplicate:'Duplicate',
      lock:'Lock',
      unlock:'Unlock',
      movement:'movement',
      moveUp:'Move Up',
      moveDown:'Move Down',
      exportAs:'Export As',
      image:'Image',
      group:'Group',
      ungroup:'Ungroup',
      copyStyle:'Copy Style',
      copy:'Copy',
      paste:'Paste',
      pasteStyle:'Paste Style',
    },
    sidebar: {
      toolbar: {
        dashboard:'Dashboard',
        newProject:'New',
        myTemplates:'Templates',
        files:'Files',
        learn:'Learn',
        shape: 'Tools',
        icons:'Assets',
        icon:'Icon',
        defaultIcons:'Default Icons',
        searchResults:'Search results',
        searchIcons:'Search Assets',
        searching:'Searching...',
        search: "Search",
        layers: 'Elements',
        history: 'History',
        documentSettings: 'Document Settings',
        editorSettings: 'Editor Settings',
        printSettings: 'Print Settings',
        print:'Print',
        dataMapping: 'Data Mapping',
        importData:'Import Data',
        dynamicPrinting:'Dynamic Printing',
        localFileUpload: 'Upload from disk',
        wooImport:'Woo',
        importFromUrl: 'Import From URL',
        dataSettings: 'Data Settings',
        dieCutTemplates: 'Diecut Templates',
        templates: 'Templates',
        socialLayouts: 'Social Layouts',
        layoutMaker: 'Layout Maker',
        sheetLayout: 'Sheet Layout',
        myLayout: 'My Layouts',
      },
      shape: {
        text: 'Text',
        barcodeBasic: 'Barcode',
        image: 'Image',
        gif:'GIF',
        video:'Video',
        audio:'Audio',
        timer:'Timer',
        qrcode: 'QRcode',
        barcode: 'Barcode',
        barcodeAdvance: 'Barcode Advance',
        rect: "Rectangle",
        triangle: "Triangle",
        polygon: "Polygon",
        circle: "Circle",
        line: "Line",
        star: "Star",
        arc: "Arc",
        oval: "Oval",
        svg:'SVG',
      },
      elements: {
        text: 'Elements',
        noElementFound:'No element found',
      },
      history:{
        noHistoryFound:'No history found',
      },
      mapping:{
        clearMappedData:'Clear mapped data',
      },
      printSettings: {
        text: "Print Settings",
        printQuality: {
          text: "Print Quality",
          low: 'Low',
          medium: 'Medium',
          high: 'High',
        },
      },
      printMode: {
        mode: 'Mode',
        staticModeText: 'In static mode, you can print the same design as many as you want.',
        dynamicModeText: 'In dynamic mode, you can print the same design based on data. All you need to import data then map your data to the current design.',
        goDataTabText: 'Click here to upload data.',
        numberOfLabels: "Label count",
        printingActivated:'printing activated',
        dynamicPrinting:'Dynamic Printing',
        info:'Info',
        importData:'Import Data',
      },
      pageSettings: {
        text: "Page Settings",
        paperSize:'Paper Size',
        marginLeft: "Margin Left",
        marginTop: "Margin Top",
        customPageSize: "Custom page Size",
        labelSize: "Label Settings",
        paddingLeft: "Padding Left",
        paddingTop: "Padding Top",
        sameAsPageSize: "Same as page size",
        apply: "Apply",
      },
      dataMapping: {
        text: "Data Mapping",
      }
    },
    option: {
      new:'New Template',
      file: 'File',
      downloadAsImage: 'Download as Image',
      preview:'Preview',
      save: "Save",
      saveAs: "Save as",
      saveAsTemplate: 'Save as Template',
      saveAsLayout: 'Save as Layout',
      export: "Export Template",
      import: "Import Template",
      unitConverter: "Unit Converter",
      deleteSavedData: "Delete saved data",
      save_to_media_library:"Save as Image",
    },
    properties: {
      text: "properties",
      noElementSelected: "Select an element to show it's properties here",
      opacity: "Opacity",
      shadow: "Shadow",
      backgroundColorText:'Background Color',
      color:'Fill Color',
      backgroundSettings:'Background Settings',
      fitInViewport:'Fit in viewport',
      enableRuler:'Enable Ruler',
      rulerTickSize:'Ruler Tick Size',
      rulerTickSpacking:'Ruler Tick Spacing',
      rulerFontSize:'Ruler Font Size',
      enableGridAndSnapping:'Enable Grid & Snapping',
      blockSnapSize:'Block Snap Size',
    },
    data: {
      noDataToPreview: 'Upload or import data to preview here',
      clickToUpload: "Click to upload data",
      import: "Import",
      ignoreFirstRow: "Ignore first row",
      dataSelection: "Data selection",
      printAllData: "Print all data",
      printSelectedData: "Print selected data",
      ignoreSelectedData: "Ignore selected data",
      range: "Range",
      from: "From",
      to: "To",
    }
  },
  cn: {
    common: {
      width: "宽度",
      height: "高度",
      pageWidth: "页面宽度",
      pageHeight: "页面高度",
      cellWidth: "标签宽度",
      cellHeight: "标签高度",
      count: "标签数量",
      cellPadding: "标签填充",
      cellPaddingLeft: "标签向左填充",
      cellPaddingTop: "标签填充顶部",
      pageMargin: "页边距",
      pageMarginLeft: "左页边距",
      pageMarginTop: "页边距顶部",
      new:'新的',
      applyLayout:'应用布局',
    },
    header: {
      menu: {
        designer: '编辑',
        data: '数据',
        templates: '模板',
        layouts: '布局',
        save: "救球",
        print: "打印",
      }
    },
    editor: {
      settings: {
        btnDelete: '删除所选',
        btnDuplicate: '复制',
        btnZoomIn: '放大',
        btnZoomOut: '缩小',
        fitInViewport:'适合视口',
        fillInViewport:'填充视口',
        btnMoveUp: '提升',
        btnMoveDown: '下移',
        btnClearAll: '全部清除'
      }
    },
    context:{
      delete:'删除',
      duplicate:'复制',
      lock:'锁',
      unlock:'开锁',
      movement:'移动',
      moveUp:'提升',
      moveDown:'下移',
      exportAs:'导出为',
      image:'图片',
    },
    sidebar: {
      toolbar: {
        shape: '工具',
        icons:'资产',
        icon:'图标',
        defaultIcons:'默认图标',
        searchResults:'搜索结果',
        searchIcons:'搜索资产',
        searching:'正在搜索...',
        search: "搜索",
        layers: '元素',
        history: '历史',
        documentSettings: '文档设置',
        editorSettings: '编辑器设置',
        printSettings: '打印设置',
        dataMapping: '数据映射',
        importData:'导入数据',
        dynamicPrinting:'动态打印',
        localFileUpload: '从磁盘上传',
        wooImport:'Woo',
        importFromUrl: '从 URL 导入',
        dataSettings: '数据设置',
        dieCutTemplates: '模切模板',
        templates: '模板',
        socialLayouts: '社会布局',
        layoutMaker: '版图制作器',
        sheetLayout: '图纸布局',
        myLayout: '我的布局',
      },
      shape: {
        text: '文本',
        barcodeBasic: '条码',
        image: '图片',
        qrcode: '二维码',
        barcode: '条码',
        barcodeAdvance: '条形码推进',
        rect: "矩形",
        triangle: "三角形",
        polygon: "多边形",
        circle: "圆圈",
        line: "线",
        star: "星星",
        arc: "弧",
        oval: "椭圆形",
        svg:'SVG',
      },
      elements: {
        text: '元素',
        noElementFound:'没有找到元素',
      },
      history:{
        noHistoryFound:'没有找到历史记录',
      },
      mapping:{
        clearMappedData:'清除映射数据',
      },
      printSettings: {
        text: "打印设置",
        printQuality: {
          text: "打印质量",
          low: '低的',
          medium: '中等的',
          high: '高的',
        },
      },
      printMode: {
        mode: '模式',
        staticModeText: '在静态模式下，您可以根据需要打印任意数量的相同设计。',
        dynamicModeText: '在动态模式下，您可以打印基于数据的相同设计。 您只需要导入数据，然后将您的数据映射到当前设计。',
        goDataTabText: '单击此处上传数据。',
        numberOfLabels: "标签数量",
        printingActivated:'打印激活',
        dynamicPrinting:'动态打印',
        info:'信息',
        importData:'导入数据',
      },
      pageSettings: {
        text: "页面设置",
        marginLeft: "左边距",
        marginTop: "保证金顶部",
        customPageSize: "自定义页面大小",
        labelSize: "标签设置",
        paddingLeft: "左填充",
        paddingTop: "填充顶部",
        sameAsPageSize: "与页面大小相同",
        apply: "申请",
      },
      dataMapping: {
        text: "数据映射",
      }
    },
    option: {
      new:'新的',
      file: '文件',
      downloadAsImage: '下载为图像',
      save: "救球",
      saveAs: "另存为",
      saveAsTemplate: '另存为模板',
      saveAsLayout: '另存为布局',
      export: "出口",
      import: "导入模板",
      unitConverter: "单位转换器",
      deleteSavedData: "删除保存的数据"
    },
    properties: {
      text: "特性",
      noElementSelected: "选择一个元素以在此处显示其属性",
      opacity: "不透明度",
      shadow: "阴影",
      backgroundColorText:'背景颜色',
      color:'填色',
      backgroundSettings:'背景设置',
      fitInViewport:'适合视口',
      enableRuler:'启用标尺',
      rulerTickSize:'标尺刻度大小',
      rulerTickSpacking:'标尺刻度间距',
      rulerFontSize:'标尺字体大小',
      enableGridAndSnapping:'启用网格和捕捉',
      blockSnapSize:'块快照大小',
    },
    data: {
      noDataToPreview: '上传或导入数据以在此处预览',
      clickToUpload: "点击上传数据",
      import: "进口",
      ignoreFirstRow: "忽略第一行",
      dataSelection: "数据选择",
      printAllData: "打印所有数据",
      printSelectedData: "打印选定的数据",
      ignoreSelectedData: "忽略所选数据",
      range: "范围",
      from: "从",
      to: "到",
    }
  },
  bd: {
    common: {
      width: "প্রস্থ",
      height: "উচ্চতা",
      pageWidth: "পৃষ্ঠার প্রস্থ",
      pageHeight: "পৃষ্ঠার উচ্চতা",
      cellWidth: "লেবেল প্রস্থ",
      cellHeight: "লেবেলের উচ্চতা",
      count: "লেবেলের সংখ্যা",
      cellPadding: "লেবেল প্যাডিং",
      cellPaddingLeft: "লেবেল প্যাডিং বাম",
      cellPaddingTop: "লেবেল প্যাডিং শীর্ষ",
      pageMargin: "পৃষ্ঠা মার্জিন",
      pageMarginLeft: "পৃষ্ঠা মার্জিন বাম",
      pageMarginTop: "পৃষ্ঠা মার্জিন শীর্ষ",
      new:'নতুন',
      applyLayout:'লেআউট প্রয়োগ করুন',
    },
    header: {
      menu: {
        designer: 'নকশাকার',
        data: 'ডেটা',
        templates: 'টেমপ্লেট',
        layouts: 'বিন্যাস',
        save: "সংরক্ষণ",
        print: "ছাপা",
      }
    },
    editor: {
      settings: {
        btnDelete: 'মুছে নির্বাচিত',
        btnDuplicate: 'দ্বিগুণ',
        btnZoomIn: 'প্রসারিত করো',
        btnZoomOut: 'ছোট করা',
        fitInViewport:'ভিউপোর্টে ফিট করুন',
        fillInViewport:'ভিউপোর্ট পূরণ করুন',
        btnMoveUp: 'উপরে উঠানো',
        btnMoveDown: 'নিচে যাও',
        btnClearAll: 'সব পরিষ্কার করে দাও'
      }
    },
    context:{
      delete:'মুছে ফেলা',
      duplicate:'দ্বিগুণিত',
      lock:'তালা',
      unlock:'আনলক করুন',
      movement:'নড়াচড়া',
      moveUp:'উপরে উঠানো',
      moveDown:'নিচে যাও',
      exportAs:'হিসাবে রপ্তানি করুন',
      image:'ছবি',
    },
    sidebar: {
      toolbar: {
        shape: 'টুলস',
        icons:'সম্পদ',
        icon:'আইকন',
        defaultIcons:'ডিফল্ট আইকন',
        searchResults:'অনুসন্ধান ফলাফল',
        searchIcons:'সম্পদ অনুসন্ধান করুন',
        searching:'অনুসন্ধান করা হচ্ছে...',
        search: "অনুসন্ধান করুন",
        layers: 'উপাদান',
        history: 'ইতিহাস',
        documentSettings: 'ডকুমেন্ট সেটিংস',
        editorSettings: 'সম্পাদক সেটিংস',
        printSettings: 'প্রিন্ট সেটিংস',
        dataMapping: 'তথ্য ম্যাপিং',
        importData:'তথ্য আমদানি',
        dynamicPrinting:'ডাইনামিক প্রিন্টিং',
        localFileUpload: 'ডিস্ক থেকে আপলোড করুন',
        wooImport:'Woo',
        importFromUrl: 'URL থেকে আমদানি করুন',
        dataSettings: 'ডেটা সেটিংস',
        dieCutTemplates: 'Diecut টেমপ্লেট',
        templates: 'টেমপ্লেট',
        socialLayouts: 'সামাজিক বিন্যাস',
        layoutMaker: 'লেআউট মেকার',
        sheetLayout: 'শীট লেআউট',
        myLayout: 'আমার লেআউট',
      },
      shape: {
        text: 'লেখা',
        barcodeBasic: 'বারকোড',
        image: 'ছবি',
        qrcode: 'QR কোড',
        barcode: 'বারকোড',
        barcodeAdvance: 'বারকোড অগ্রিম',
        rect: "আয়তক্ষেত্র",
        triangle: "ত্রিভুজ",
        polygon: "বহুভুজ",
        circle: "বৃত্ত",
        line: "লাইন",
        star: "তারা",
        arc: "অর্ক",
        oval: "ডিম্বাকার",
        svg:'SVG',
      },
      elements: {
        text: 'উপাদান',
        noElementFound:'কোনো উপাদান পাওয়া যায়নি',
      },
      history:{
        noHistoryFound:'কোনো ইতিহাস পাওয়া যায়নি',
      },
      mapping:{
        clearMappedData:'ম্যাপ করা ডেটা সাফ করুন',
      },
      printSettings: {
        text: "প্রিন্ট সেটিংস",
        printQuality: {
          text: "মুদ্রণ মান",
          low: 'কম',
          medium: 'মধ্যম',
          high: 'উচ্চ',
        },
      },
      printMode: {
        mode: 'মোড',
        staticModeText: 'স্ট্যাটিক মোডে, আপনি যত খুশি একই ডিজাইন প্রিন্ট করতে পারবেন।',
        dynamicModeText: 'ডাইনামিক মোডে, আপনি ডেটার উপর ভিত্তি করে একই ডিজাইন প্রিন্ট করতে পারেন। আপনার যা ডেটা আমদানি করতে হবে তারপরে বর্তমান ডিজাইনে আপনার ডেটা ম্যাপ করুন৷',
        goDataTabText: 'ডেটা আপলোড করতে এখানে ক্লিক করুন।',
        numberOfLabels: "লেবেলের সংখ্যা",
        printingActivated:'মুদ্রণ সক্রিয়',
        dynamicPrinting:'ডায়নামিক প্রিন্টিং',
        info:'তথ্য',
        importData:'তথ্য আমদানি',
      },
      pageSettings: {
        text: "পৃষ্ঠা সেটিংস",
        marginLeft: "মার্জিন বাম",
        marginTop: "মার্জিন শীর্ষ",
        customPageSize: "কাস্টম পেজ সাইজ",
        labelSize: "লেবেল সেটিংস",
        paddingLeft: "প্যাডিং বাম",
        paddingTop: "প্যাডিং শীর্ষ",
        sameAsPageSize: "পৃষ্ঠার আকারের মতো",
        apply: "আবেদন করুন",
      },
      dataMapping: {
        text: "তথ্য ম্যাপিং",
      }
    },
    option: {
      new:'নতুন',
      file: 'ফাইল',
      downloadAsImage: 'ছবি হিসেবে ডাউনলোড করুন',
      save: "সংরক্ষণ",
      saveAs: "সংরক্ষণ করুন",
      saveAsTemplate: 'ফর্মা হিসেবে সংরক্ষণ',
      saveAsLayout: 'লেআউট হিসাবে সংরক্ষণ করুন',
      export: "রপ্তানি",
      import: "টেমপ্লেট আমদানি করুন",
      unitConverter: "ইউনিট কনভার্টার",
      deleteSavedData: "সংরক্ষিত ডেটা মুছুন"
    },
    properties: {
      text: "বৈশিষ্ট্য",
      noElementSelected: "এটির বৈশিষ্ট্য এখানে দেখানোর জন্য একটি উপাদান নির্বাচন করুন",
      opacity: "অস্বচ্ছতা",
      shadow: "ছায়া",
      backgroundColorText:'পেছনের রঙ',
      color:'রঙ পূরণ করুন',
      backgroundSettings:'পটভূমি সেটিংস',
      fitInViewport:'ভিউপোর্টে ফিট করুন',
      enableRuler:'শাসক সক্ষম করুন',
      rulerTickSize:'রুলার টিক সাইজ',
      rulerTickSpacking:'রুলার টিক স্পেসিং',
      rulerFontSize:'রুলার ফন্ট সাইজ',
      enableGridAndSnapping:'গ্রিড এবং স্ন্যাপিং সক্ষম করুন',
      blockSnapSize:'ব্লক স্ন্যাপ আকার',
    },
    data: {
      noDataToPreview: 'এখানে পূর্বরূপ দেখতে ডেটা আপলোড বা আমদানি করুন',
      clickToUpload: "ডেটা আপলোড করতে ক্লিক করুন",
      import: "আমদানি",
      ignoreFirstRow: "প্রথম সারি উপেক্ষা করুন",
      dataSelection: "ডেটা নির্বাচন",
      printAllData: "সমস্ত ডেটা প্রিন্ট করুন",
      printSelectedData: "নির্বাচিত ডেটা প্রিন্ট করুন",
      ignoreSelectedData: "নির্বাচিত ডেটা উপেক্ষা করুন",
      range: "পরিসর",
      from: "থেকে",
      to: "To",
    }
  },
  de: {
    common: {
      width: "Breite",
      height: "Höhe",
      pageWidth: "Seitenbreite",
      pageHeight: "Seitenhöhe",
      cellWidth: "Etikettenbreite",
      cellHeight: "Etikettenhöhe",
      count: "Anzahl der Etiketten",
      cellPadding: "Beschriftungspolsterung",
      cellPaddingLeft: "Beschriftungspolster links",
      cellPaddingTop: "Etikettenpolster oben",
      pageMargin: "Seitenrand",
      pageMarginLeft: "Seitenrand links",
      pageMarginTop: "Seitenrand oben",
      new:'Neu',
      applyLayout:'Layout anwenden',
    },
    header: {
      menu: {
        designer: 'Editor',
        data: 'Daten',
        templates: 'Vorlagen',
        layouts: 'Grundrisse',
        save: "Speichern",
        print: "Drucken",
      }
    },
    editor: {
      settings: {
        btnDelete: 'Ausgewählte löschen',
        btnDuplicate: 'Duplikat',
        btnZoomIn: 'Hineinzoomen',
        btnZoomOut: 'Rauszoomen',
        fitInViewport:'An Ansichtsfenster anpassen',
        fillInViewport:'Ansichtsfenster ausfüllen',
        btnMoveUp: 'Nach oben bewegen',
        btnMoveDown: 'Sich abwärts bewegen',
        btnClearAll: 'Alles löschen'
      }
    },
    context:{
      delete:'Löschen',
      duplicate:'Duplikat',
      lock:'Sperren',
      unlock:'Freischalten',
      movement:'Bewegung',
      moveUp:'Nach oben bewegen',
      moveDown:'Sich abwärts bewegen',
      exportAs:'Exportieren als',
      image:'Bild',
    },
    sidebar: {
      toolbar: {
        shape: 'Werkzeug',
        icons:'Vermögenswerte',
        icon:'Symbol',
        defaultIcons:'Standardsymbole',
        searchResults:'Suchergebnisse',
        searchIcons:'Assets durchsuchen',
        searching:'Suche...',
        search: "Suche",
        layers: 'Elemente',
        history: 'Geschichte',
        documentSettings: 'Dokumenteinstellungen',
        editorSettings: 'Editor-Einstellungen',
        printSettings: 'Druckeinstellungen',
        dataMapping: 'Datenzuordnung',
        importData:'Daten importieren',
        dynamicPrinting:'Dynamisches Drucken',
        localFileUpload: 'Hochladen von der Festplatte',
        wooImport:'Woo',
        importFromUrl: 'Aus URL importieren',
        dataSettings: 'Dateneinstellungen',
        dieCutTemplates: 'Stanzvorlagen',
        templates: 'Vorlagen',
        socialLayouts: 'Soziale Layouts',
        layoutMaker: 'Layout-Maker',
        sheetLayout: 'Blattlayout',
        myLayout: 'Meine Layouts',
      },
      shape: {
        text: 'Text',
        barcodeBasic: 'Strichcode',
        image: 'Bild',
        qrcode: 'QR-Code',
        barcode: 'Strichcode',
        barcodeAdvance: 'Barcode-Fortschritt',
        rect: "Rechteck",
        triangle: "Dreieck",
        polygon: "Vieleck",
        circle: "Kreis",
        line: "Linie",
        star: "Stern",
        arc: "Bogen",
        oval: "Oval",
        svg:'SVG',
      },
      elements: {
        text: 'Elemente',
        noElementFound:'Kein Element gefunden',
      },
      history:{
        noHistoryFound:'Kein Verlauf gefunden',
      },
      mapping:{
        clearMappedData:'Kartierte Daten löschen',
      },
      printSettings: {
        text: "Druckeinstellungen",
        printQuality: {
          text: "Druckqualität",
          low: 'Niedrig',
          medium: 'Mittel',
          high: 'Hoch',
        },
      },
      printMode: {
        mode: 'Modus',
        staticModeText: 'Im statischen Modus können Sie dasselbe Design beliebig oft drucken.',
        dynamicModeText: 'Im dynamischen Modus können Sie dasselbe Design basierend auf Daten drucken. Alles, was Sie brauchen, um Daten zu importieren und Ihre Daten dann dem aktuellen Design zuzuordnen.',
        goDataTabText: 'Klicken Sie hier, um Daten hochzuladen.',
        numberOfLabels: "Anzahl der Etiketten",
        printingActivated:'Drucken aktiviert',
        dynamicPrinting:'Dynamisches Drucken',
        info:'Die Info',
        importData:'Daten importieren',
      },
      pageSettings: {
        text: "Seiteneinstellungen",
        marginLeft: "Rand übrig",
        marginTop: "Rand oben",
        customPageSize: "Benutzerdefinierte Seitengröße",
        labelSize: "Etiketteneinstellungen",
        paddingLeft: "Polsterung links",
        paddingTop: "Polsterung oben",
        sameAsPageSize: "Gleich wie Seitengröße",
        apply: "Anwenden",
      },
      dataMapping: {
        text: "Datenzuordnung",
      }
    },
    option: {
      new:'Neu',
      file: 'Datei',
      downloadAsImage: 'Als Bild herunterladen',
      save: "Speichern",
      saveAs: "Speichern als",
      saveAsTemplate: 'Als Vorlage speichern',
      saveAsLayout: 'Als Layout speichern',
      export: "Export",
      import: "Vorlage importieren",
      unitConverter: "Einheitenumwandler",
      deleteSavedData: "Gespeicherte Daten löschen"
    },
    properties: {
      text: "Eigenschaften",
      noElementSelected: "Wählen Sie ein Element aus, um seine Eigenschaften hier anzuzeigen",
      opacity: "Opazität",
      shadow: "Schatten",
      backgroundColorText:'Hintergrundfarbe',
      color:'Füllfarbe',
      backgroundSettings:'Hintergrundeinstellungen',
      fitInViewport:'In Ansichtsfenster einpassen',
      enableRuler:'Lineal aktivieren',
      rulerTickSize:'Lineal Tick-Größe',
      rulerTickSpacking:'Abstand der Linealstriche',
      rulerFontSize:'Schriftgröße des Lineals',
      enableGridAndSnapping:'Aktivieren Sie Raster und Fangen',
      blockSnapSize:'Snap-Größe blockieren',
    },
    data: {
      noDataToPreview: 'Hier können Sie Daten für die Vorschau hochladen oder importieren',
      clickToUpload: "Klicken Sie hier, um Daten hochzuladen",
      import: "Importieren",
      ignoreFirstRow: "Erste Reihe ignorieren",
      dataSelection: "Datenauswahl",
      printAllData: "Alle Daten drucken",
      printSelectedData: "Ausgewählte Daten drucken",
      ignoreSelectedData: "Ausgewählte Daten ignorieren",
      range: "Bereich",
      from: "Von",
      to: "Zu",
    }
  },
  sa: {
    common: {
      width: "عرض",
      height: "ارتفاع",
      pageWidth: "عرض الصفحة",
      pageHeight: "ارتفاع الصفحة",
      cellWidth: "عرض التسمية",
      cellHeight: "ارتفاع التسمية",
      count: "عدد الملصقات",
      cellPadding: "حشوة التسمية",
      cellPaddingLeft: "ترك مساحة في التسمية لليسار",
      cellPaddingTop: "أعلى الحشو التسمية",
      pageMargin: "هامش الصفحة",
      pageMarginLeft: "هامش الصفحة الأيسر",
      pageMarginTop: "هامش الصفحة الأعلى",
      new:'جديد',
      applyLayout:'تطبيق التخطيط',
    },
    header: {
      menu: {
        designer: 'محرر',
        data: 'بيانات',
        templates: 'القوالب',
        layouts: 'التخطيطات',
        save: "يحفظ",
        print: "مطبعة",
      }
    },
    editor: {
      settings: {
        btnDelete: 'احذف المختار',
        btnDuplicate: 'ينسخ',
        btnZoomIn: 'تكبير',
        btnZoomOut: 'تصغير',
        fitInViewport:'تناسب في منفذ العرض',
        fillInViewport:'املأ منفذ العرض',
        btnMoveUp: 'تحرك',
        btnMoveDown: 'تحرك لأسفل',
        btnClearAll: 'امسح الكل'
      }
    },
    context:{
      delete:'حذف',
      duplicate:'ينسخ',
      lock:'قفل',
      unlock:'الغاء القفل',
      movement:'حركة',
      moveUp:'تحرك',
      moveDown:'تحرك لأسفل',
      exportAs:'تصدير بتنسيق',
      image:'صورة',
    },
    sidebar: {
      toolbar: {
        shape: 'أدوات',
        icons:'أصول',
        icon:'أيقونة',
        defaultIcons:'الرموز الافتراضية',
        searchResults:'نتائج البحث',
        searchIcons:'البحث في الأصول',
        searching:'يبحث...',
        search: "بحث",
        layers: 'عناصر',
        history: 'تاريخ',
        documentSettings: 'إعدادات المستند',
        editorSettings: 'إعدادات المحرر',
        printSettings: 'إعدادات الطباعة',
        dataMapping: 'تعيين البيانات',
        importData:'بيانات الاستيراد',
        dynamicPrinting:'طباعة ديناميكية',
        localFileUpload: 'تحميل من القرص',
        wooImport:'Woo',
        importFromUrl: 'استيراد من URL',
        dataSettings: 'إعدادات البيانات',
        dieCutTemplates: 'قوالب Diecut',
        templates: 'القوالب',
        socialLayouts: 'التخطيطات الاجتماعية',
        layoutMaker: 'صانع التخطيط',
        sheetLayout: 'تخطيط الورقة',
        myLayout: 'تخطيطاتي',
      },
      shape: {
        text: 'نص',
        barcodeBasic: 'الباركود',
        image: 'صورة',
        qrcode: 'رمز الاستجابة السريعة',
        barcode: 'الباركود',
        barcodeAdvance: 'تقدم الباركود',
        rect: "مستطيل",
        triangle: "مثلث",
        polygon: "مضلع",
        circle: "دائرة",
        line: "خط",
        star: "نجمة",
        arc: "قوس",
        oval: "بيضاوي",
        svg:'SVG',
      },
      elements: {
        text: 'عناصر',
        noElementFound:'لم يتم العثور على عنصر',
      },
      history:{
        noHistoryFound:'لم يتم العثور على سجل',
      },
      mapping:{
        clearMappedData:'مسح البيانات المعينة',
      },
      printSettings: {
        text: "إعدادات الطباعة",
        printQuality: {
          text: "جودة الطباعة",
          low: 'قليل',
          medium: 'متوسط',
          high: 'عالٍ',
        },
      },
      printMode: {
        mode: 'الوضع',
        staticModeText: 'في الوضع الثابت ، يمكنك طباعة نفس التصميم بقدر ما تريد.',
        dynamicModeText: 'في الوضع الديناميكي ، يمكنك طباعة نفس التصميم بناءً على البيانات. كل ما تحتاجه لاستيراد البيانات ثم تعيين بياناتك للتصميم الحالي.',
        goDataTabText: 'انقر هنا لتحميل البيانات.',
        numberOfLabels: "عدد الملصقات",
        printingActivated:'تنشيط الطباعة',
        dynamicPrinting:'طباعة ديناميكية',
        info:'معلومات',
        importData:'بيانات الاستيراد'
      },
      pageSettings: {
        text: "إعدادات الصفحة",
        marginLeft: "الهامش الأيسر",
        marginTop: "أعلى الهامش",
        customPageSize: "حجم الصفحة المخصص",
        labelSize: "إعدادات التسمية",
        paddingLeft: "المساحة المتروكة لليسار",
        paddingTop: "أعلى الحشو",
        sameAsPageSize: "نفس حجم الصفحة",
        apply: "تطبيق",
      },
      dataMapping: {
        text: "تعيين البيانات",
      }
    },
    option: {
      new:'جديد',
      file: 'ملف',
      downloadAsImage: 'تنزيل كصورة',
      save: "يحفظ",
      saveAs: "حفظ باسم",
      saveAsTemplate: 'حفظ كقالب',
      saveAsLayout: 'حفظ كتخطيط',
      export: "يصدّر",
      import: "قالب الاستيراد",
      unitConverter: "محول وحدات",
      deleteSavedData: "حذف البيانات المحفوظة"
    },
    properties: {
      text: "الخصائص",
      noElementSelected: "حدد عنصرًا لإظهار خصائصه هنا",
      opacity: "التعتيم",
      shadow: "ظل",
      backgroundColorText:'لون الخلفية',
      color:'لون التعبئة',
      backgroundSettings:'إعدادات الخلفية',
      fitInViewport:'تناسب منفذ العرض',
      enableRuler:'تمكين المسطرة',
      rulerTickSize:'حجم علامة المسطرة',
      rulerTickSpacking:'التباعد بين علامات المسطرة',
      rulerFontSize:'حجم خط المسطرة',
      enableGridAndSnapping:'تمكين الشبكة والالتقاط',
      blockSnapSize:'حجم التقط الكتلة',
    },
    data: {
      noDataToPreview: 'تحميل أو استيراد البيانات للمعاينة هنا',
      clickToUpload: "انقر لتحميل البيانات",
      import: "يستورد",
      ignoreFirstRow: "تجاهل الصف الأول",
      dataSelection: "اختيار البيانات",
      printAllData: "طباعة كافة البيانات",
      printSelectedData: "طباعة البيانات المحددة",
      ignoreSelectedData: "تجاهل البيانات المحددة",
      range: "نطاق",
      from: "من",
      to: "إلى",
    }
  },
  il: {
    common: {
      width: "רוֹחַב",
      height: "גוֹבַה",
      pageWidth: "רוחב עמוד",
      pageHeight: "גובה העמוד",
      cellWidth: "רוחב תווית",
      cellHeight: "גובה התווית",
      count: "מספר תוויות",
      cellPadding: "ריפוד תווית",
      cellPaddingLeft: "ריפוד תווית שמאלה",
      cellPaddingTop: "טופ ריפוד תווית",
      pageMargin: "שולי עמוד",
      pageMarginLeft: "שולי עמוד שמאלה",
      pageMarginTop: "עמוד שולי למעלה",
      new:'חָדָשׁ',
      applyLayout:'החל פריסה',
    },
    header: {
      menu: {
        designer: 'עוֹרֵך',
        data: 'נתונים',
        templates: 'תבניות',
        layouts: 'פריסות',
        save: "להציל",
        print: "הדפס",
      }
    },
    editor: {
      settings: {
        btnDelete: 'מחק את הנבחר',
        btnDuplicate: 'לְשַׁכְפֵּל',
        btnZoomIn: 'לְהִתְמַקֵד',
        btnZoomOut: 'להקטין את התצוגה',
        fitInViewport:'התאמה ל-Viewport',
        fillInViewport:'מלאו נקודת מבט',
        btnMoveUp: 'לזוז למעלה',
        btnMoveDown: 'לרדת',
        btnClearAll: 'נקה הכל'
      }
    },
    context:{
      delete:'לִמְחוֹק',
      duplicate:'לְשַׁכְפֵּל',
      lock:'לנעול',
      unlock:'לבטל נעילה',
      movement:'תְנוּעָה',
      moveUp:'לזוז למעלה',
      moveDown:'לרדת',
      exportAs:'ייצא בשם',
      image:'תמונה',
    },
    sidebar: {
      toolbar: {
        shape: 'כלים',
        icons:'נכסים',
        icon:'סמל',
        defaultIcons:'סמלי ברירת מחדל',
        searchResults:'תוצאות חיפוש',
        searchIcons:'חיפוש נכסים',
        searching:'מחפש...',
        search: "לחפש",
        layers: 'אלמנטים',
        history: 'הִיסטוֹרִיָה',
        documentSettings: 'הגדרות מסמך',
        editorSettings: 'הגדרות עורך',
        printSettings: 'הגדרות הדפסה',
        dataMapping: 'מיפוי נתונים',
        importData:'ייבוא נתונים',
        dynamicPrinting:'הדפסה דינמית',
        localFileUpload: 'העלה מהדיסק',
        wooImport:'Woo',
        importFromUrl: 'ייבוא מ-URL',
        dataSettings: 'הגדרות נתונים',
        dieCutTemplates: 'תבניות גזרה',
        templates: 'תבניות',
        socialLayouts: 'פריסות חברתיות',
        layoutMaker: 'יוצר פריסה',
        sheetLayout: 'פריסת גיליון',
        myLayout: 'הפריסות שלי',
      },
      shape: {
        text: 'טֶקסט',
        barcodeBasic: 'ברקוד',
        image: 'תמונה',
        qrcode: 'קוד QR',
        barcode: 'ברקוד',
        barcodeAdvance: 'ברקוד מתקדם',
        rect: "מַלבֵּן",
        triangle: "משולש",
        polygon: "מְצוּלָע",
        circle: "מעגל",
        line: "קַו",
        star: "כוכב",
        arc: "קֶשֶׁת",
        oval: "סְגַלגַל",
        svg:'SVG',
      },
      elements: {
        text: 'אלמנטים',
        noElementFound:'לא נמצא רכיב',
      },
      history:{
        noHistoryFound:'לא נמצאה היסטוריה',
      },
      mapping:{
        clearMappedData:'נקה נתונים ממופים',
      },
      printSettings: {
        text: "הגדרות הדפסה",
        printQuality: {
          text: "איכות הדפסה",
          low: 'נָמוּך',
          medium: 'בינוני',
          high: 'גָבוֹהַ',
        },
      },
      printMode: {
        mode: 'מצב',
        staticModeText: 'במצב סטטי, אתה יכול להדפיס את אותו עיצוב כמה שאתה רוצה.',
        dynamicModeText: 'במצב דינמי, ניתן להדפיס את אותו עיצוב על סמך נתונים. כל מה שאתה צריך כדי לייבא נתונים ואז למפות את הנתונים שלך לעיצוב הנוכחי.',
        goDataTabText: 'לחץ כאן כדי להעלות נתונים.',
        numberOfLabels: "מספר תוויות",
        printingActivated:'ההדפסה הופעלה',
        dynamicPrinting:'הדפסה דינמית',
        info:'מידע',
        importData:'ייבוא נתונים',
      },
      pageSettings: {
        text: "הגדרות עמוד",
        marginLeft: "שוליים שמאלה",
        marginTop: "שוליים למעלה",
        customPageSize: "גודל עמוד מותאם אישית",
        labelSize: "הגדרות תווית",
        paddingLeft: "ריפוד שמאלה",
        paddingTop: "טופ ריפוד",
        sameAsPageSize: "זהה לגודל העמוד",
        apply: "להגיש מועמדות",
      },
      dataMapping: {
        text: "מיפוי נתונים",
      }
    },
    option: {
      new:'חָדָשׁ',
      file: 'קוֹבֶץ',
      downloadAsImage: 'הורד כתמונה',
      save: "להציל",
      saveAs: "שמור כ",
      saveAsTemplate: 'שמור כתבנית',
      saveAsLayout: 'שמור כפריסה',
      export: "יְצוּא",
      import: "ייבוא תבנית",
      unitConverter: "ממיר יחידה",
      deleteSavedData: "מחק נתונים שנשמרו"
    },
    properties: {
      text: "נכסים",
      noElementSelected: "בחר אלמנט כדי להציג את המאפיינים שלו כאן",
      opacity: "אֲטִימוּת",
      shadow: "צֵל",
      backgroundColorText:'צבע רקע',
      color:'צבע מילוי',
      backgroundSettings:'הגדרות רקע',
      fitInViewport:'מתאים לנקודת מבט',
      enableRuler:'אפשר סרגל',
      rulerTickSize:'גודל טיק של סרגל',
      rulerTickSpacking:'מרווח סימון סרגל',
      rulerFontSize:'גודל גופן סרגל',
      enableGridAndSnapping:'Enable Grid & Snapping',
      blockSnapSize:'Block Snap Size',
    },
    data: {
      noDataToPreview: 'העלה או ייבא נתונים לתצוגה מקדימה כאן',
      clickToUpload: "לחץ כדי להעלות נתונים",
      import: "יְבוּא",
      ignoreFirstRow: "התעלם מהשורה הראשונה",
      dataSelection: "בחירת נתונים",
      printAllData: "הדפס את כל הנתונים",
      printSelectedData: "הדפס נתונים נבחרים",
      ignoreSelectedData: "התעלם מהנתונים שנבחרו",
      range: "טווח",
      from: "מ",
      to: "ל",
    }
  },
  es: {
    common: {
      width: "Ancho",
      height: "Altura",
      pageWidth: "Ancho de página",
      pageHeight: "Altura de página",
      cellWidth: "Ancho de etiqueta",
      cellHeight: "Altura de la etiqueta",
      count: "Número de etiquetas",
      cellPadding: "Relleno de etiqueta",
      cellPaddingLeft: "Relleno de etiqueta a la izquierda",
      cellPaddingTop: "Parte superior con relleno de etiquetas",
      pageMargin: "Margen de página",
      pageMarginLeft: "Margen de página izquierdo",
      pageMarginTop: "Margen superior de la página",
      new:'Nuevo',
      applyLayout:'Aplicar diseño',
    },
    header: {
      menu: {
        designer: 'Diseñador',
        data: 'Datos',
        templates: 'Plantillas',
        layouts: 'Diseños',
        save: "Ahorrar",
        print: "Imprimir",
      }
    },
    editor: {
      settings: {
        btnDelete: 'Eliminar seleccionado',
        btnDuplicate: 'Duplicado',
        btnZoomIn: 'Acercarse',
        btnZoomOut: 'Disminuir el zoom',
        fitInViewport:'Encajar en ventana gráfica',
        fillInViewport:'Rellenar ventana gráfica',
        btnMoveUp: 'Ascender',
        btnMoveDown: 'Mover hacia abajo',
        btnClearAll: 'Limpiar todo'
      }
    },
    context:{
      delete:'Borrar',
      duplicate:'Duplicado',
      lock:'Cerrar con llave',
      unlock:'desbloquear',
      movement:'movimienot',
      moveUp:'Ascender',
      moveDown:'Mover hacia abajo',
      exportAs:'Exportar cómo',
      image:'Imagen',
    },
    sidebar: {
      toolbar: {
        shape: 'Herramientas',
        icons:'Activos',
        icon:'Icono',
        defaultIcons:'Iconos predeterminados',
        searchResults:'Resultados de la búsqueda',
        searchIcons:'Buscar activos',
        searching:'Buscando...',
        search: "Búsqueda",
        layers: 'Elementos',
        history: 'Historia',
        documentSettings: 'Configuración del documento',
        editorSettings: 'Configuración del editor',
        printSettings: 'Configuración de impresión',
        dataMapping: 'Mapeo de datos',
        importData:'Datos de importacion',
        dynamicPrinting:'Impresión dinámica',
        localFileUpload: 'Subir desde disco',
        wooImport:'Woo',
        importFromUrl: 'Importar desde URL',
        dataSettings: 'Configuración de datos',
        dieCutTemplates: 'Plantillas troqueladas',
        templates: 'Plantillas',
        socialLayouts: 'Diseños sociales',
        layoutMaker: 'Creador de diseño',
        sheetLayout: 'Diseño de hoja',
        myLayout: 'Mis diseños',
      },
      shape: {
        text: 'Texto',
        barcodeBasic: 'Código de barras',
        image: 'Imagen',
        qrcode: 'Código QR',
        barcode: 'Código de barras',
        barcodeAdvance: 'Código de barras avanzado',
        rect: "Rectángulo",
        triangle: "Triángulo",
        polygon: "Polígono",
        circle: "Círculo",
        line: "Línea",
        star: "Estrella",
        arc: "Arco",
        oval: "Oval",
        svg:'SVG',
      },
      elements: {
        text: 'Elementos',
        noElementFound:'Ningún elemento encontrado',
      },
      history:{
        noHistoryFound:'No se encontró historial',
      },
      mapping:{
        clearMappedData:'Borrar datos mapeados',
      },
      printSettings: {
        text: "Configuración de impresión",
        printQuality: {
          text: "Calidad de impresión",
          low: 'Bajo',
          medium: 'Medio',
          high: 'Alto',
        },
      },
      printMode: {
        mode: 'Modo',
        staticModeText: 'En modo estático, puede imprimir el mismo diseño tantos como desee.',
        dynamicModeText: 'En el modo dinámico, puede imprimir el mismo diseño en función de los datos. Todo lo que necesita para importar datos y luego asignar sus datos al diseño actual.',
        goDataTabText: 'Haga clic aquí para cargar datos.',
        numberOfLabels: "Número de etiquetas",
        printingActivated:'impresión activada',
        dynamicPrinting:'Impresión dinámica',
        info:'Información',
        importData:'Datos de importacion',
      },
      pageSettings: {
        text: "Configuración de página",
        marginLeft: "margen izquierdo",
        marginTop: "Margen superior",
        customPageSize: "Tamaño de página personalizado",
        labelSize: "Configuración de etiquetas",
        paddingLeft: "Relleno a la izquierda",
        paddingTop: "Acolchado superior",
        sameAsPageSize: "Lo mismo que el tamaño de página",
        apply: "Solicitar",
      },
      dataMapping: {
        text: "Mapeo de datos",
      }
    },
    option: {
      new:'Nueva',
      file: 'Archivo',
      downloadAsImage: 'Descargar como imagen',
      save: "Ahorrar",
      saveAs: "Guardar como",
      saveAsTemplate: 'Guardar como plantilla',
      saveAsLayout: 'Guardar como diseño',
      export: "Exportar",
      import: "Importar plantilla",
      unitConverter: "Convertidor de unidades",
      deleteSavedData: "Eliminar datos guardados"
    },
    properties: {
      text: "propiedades",
      noElementSelected: "Seleccione un elemento para mostrar sus propiedades aquí",
      opacity: "Opacidad",
      shadow: "Sombra",
      backgroundColorText:'Color de fondo',
      color:'Color de relleno',
      backgroundSettings:'Configuración de fondo',
      fitInViewport:'Encajar en ventana gráfica',
      enableRuler:'Habilitar regla',
      rulerTickSize:'Tamaño de marca de regla',
      rulerTickSpacking:'Espaciado entre marcas de regla',
      rulerFontSize:'Tamaño de fuente de la regla',
      enableGridAndSnapping:'Habilitar cuadrícula y ajuste',
      blockSnapSize:'Tamaño de ajuste de bloque',
    },
    data: {
      noDataToPreview: 'Cargue o importe datos para obtener una vista previa aquí',
      clickToUpload: "Haga clic para cargar datos",
      import: "Importar",
      ignoreFirstRow: "Ignorar la primera fila",
      dataSelection: "Selección de datos",
      printAllData: "Imprimir todos los datos",
      printSelectedData: "Imprimir datos seleccionados",
      ignoreSelectedData: "Ignorar datos seleccionados",
      range: "Rango",
      from: "Desde",
      to: "A",
    }
  },
}